name: sudoku
description: An API and command line tool for solving Sudoku puzzles
version: 1.0.0
#repository: https://github.com/pohara60/dart-sudoku
environment:
    sdk: ">=2.17.0 <3.0.0"

dependencies:
    args: ^2.0.0
    chalkdart: ^2.0.8

dev_dependencies:
    test: ^1.14.4

executables:
    sudoku:
